server.port=5000
spring.application.name=service-engineer

spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.datasource.initialize=false
spring.jpa.hibernate.ddl-auto = none
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
#
#spring.datasource.url=jdbc:mysql://my-sql-rds-stetig.czg8wieycmjl.us-east-1.rds.amazonaws.com:3306/APSE
#spring.security.user.name=admin
#spring.datasource.username=admin
#spring.datasource.password=Stetig2025
#spring.security.user.password=123456
#spring.security.enabled=false

spring.jpa.database-platform=org.hibernate.dialect.HANARowStoreDialect
spring.datasource.url=jdbc:sap://172.25.210.176:37615/APSE
spring.datasource.username=P00111310
spring.datasource.password=Pass12345
spring.jpa.properties.hibernate.default_schema=APSE
spring.datasource.driver-class-name=com.sap.db.jdbc.Driver


#Mail configuration
mail.from=apwasprd@apps.asianpaints.com
mail.trigger.endpoint.base-url=https://apidev.asianpaints.com
